### ISSUE TITLE
Mongo Error on slug refresh

### ISSUE THREAD

**Issue by tankerkiller125** [pauloamgomes/CockpitCMS-BetterSlugs#2]
I have a fresh install of Cockpit install, I did not modify any of the custom settings and I am getting the following errors:
```
./cp refresh-slugs --name posts
PHP Fatal error:  Uncaught Error: Call to undefined method MongoLite\Collection::getCollectionName() in /var/www/api/addons/BetterSlugs/cli/refresh-slugs.php:41
Stack trace:
#0 /var/www/api/cp(33): include()
#1 {main}
  thrown in /var/www/api/addons/BetterSlugs/cli/refresh-slugs.php on line 41
```

**Comment by pauloamgomes** [comment]
Hey @tankerkiller125 , seems something is wrong with your installation, please confirm that you are in latest release (next branch) and other cli commands (from core are working)

**Comment by tankerkiller125** [comment]
The core commands are working and the I am on the latest release, I think I may have resolved it, I originally removed Mongo because I wasn't planning on using it. I re-added Mongo and the PHP extension and I think its working now.

**Comment by slowdub** [comment]
@pauloamgomes 
I get this error too. I'm using SQLite version. This seems to be the same issue as here:
https://github.com/pauloamgomes/CockpitCMS-Helpers/issues/3

and just as there, the `$collection_name` is defined [here](https://github.com/pauloamgomes/CockpitCMS-BetterSlugs/blob/master/cli/refresh-slugs.php#L41) but not used. 
Removing that line fixes the issue for me. Here is the PR:
https://github.com/pauloamgomes/CockpitCMS-BetterSlugs/pull/3
