### ISSUE TITLE
Slug dynamic elements are not created.

### ISSUE THREAD

**Issue by nektobit** [pauloamgomes/CockpitCMS-BetterSlugs#5]
When I create a link, only the static elements of "blog /" are applied; [calback] and [field] are not applied. I use wamp "open server", cp ver 0.9.0
```
PHP Version | 7.1.22
PHP SAPI | apache2handler
System | Windows NT NEKTOBIT 10.0 build 18362 (Windows 10) AMD64
Loaded Extensions | Core, bcmath, calendar, ctype, date, filter, hash, iconv, json, mcrypt, SPL, pcre, readline, Reflection, session, standard, mysqlnd, tokenizer, zip, zlib, libxml, dom, PDO, bz2, SimpleXML, xml, wddx, xmlreader, xmlwriter, apache2handler, mbstring, openssl, curl, exif, fileinfo, ftp, gd, gettext, igbinary, imap, mongodb, mysqli, odbc, Phar, PDFlib, pdo_mysql, pdo_pgsql, pdo_sqlite, redis, soap, sockets, sqlite3, timezonedb, xmlrpc, xsl
Max. execution time | 180 sec.
OPCache enabled | NO
Memory limit | 1536M
Upload file size limit | 100M
Realpath Cache | 2048k / 600 (ttl)
```
![image](https://user-images.githubusercontent.com/5194945/59196650-945c9800-8bd2-11e9-9544-b7dc4c9f947a.png)
![image](https://user-images.githubusercontent.com/5194945/59196680-a8a09500-8bd2-11e9-9d6e-83009a58ab41.png)

**Comment by nektobit** [comment]
Ok, i think i understand:
"[field:term1]" - working
"[field:term1]/and-some" - working
"[field:term1]-and-some" - not working

**Comment by pauloamgomes** [comment]
Hi @nektobit , sorry for late answer, but can you provide more details on what you want to achieve? If you are using callback as token you need to implement the function you are providing, e.g. slugUniqId

The latest example you provided for field, the implementation only supported tokens between slashes..  happy to handle a PR that enhances that further..

In such case you can handle that functionality by using a callback token, e.g.:

`/blogs/[callback:getBlogTerm]`

```php
function getBlogTerm($entry) {
   return "{$entry['term1']}-and-some";
}
```
