### ISSUE TITLE
Typo and issue on cli generation

### ISSUE THREAD

**Issue by jasonday** [pauloamgomes/CockpitCMS-BetterSlugs#6]
Note: `wirteln` instead of `writeln`

https://github.com/pauloamgomes/CockpitCMS-BetterSlugs/blob/7e882f7e862758ffafbe152487c9ccc14d1b92a3/cli/refresh-slugs.php#L56

Either way, when updating/refreshing in cli, i'm getting the following error:

```
 - Field slug not found!
PHP Warning:  Use of undefined constant entry - assumed 'entry' (this will throw an Error in a future version of PHP) in /apps/myapps/html/cockpit/addons/BetterSlugs/cli/refresh-slugs.php on line 56
PHP Warning:  Use of undefined constant _id - assumed '_id' (this will throw an Error in a future version of PHP) in /apps/myapps/html/cockpit/addons/BetterSlugs/cli/refresh-slugs.php on line 56
PHP Notice:  Undefined variable: entry_id in /apps/myapps/html/cockpit/addons/BetterSlugs/cli/refresh-slugs.php on line 56
```

My config: 
```
{
  "format": "[collection:name]/[field:aria_property]"
}
```

Note: It seems to fail on entries that have not been 'touched' yet (meaning, the entry has not been opened/saved since adding the slug field). Additionally, it seems to ignore `[collection:name]`

**Comment by pauloamgomes** [comment]
Closed via #7

**Comment by jasonday** [comment]
@pauloamgomes do you have any insight on the second issue?

**Comment by pauloamgomes** [comment]
HI @jasonday , apologies for the delay. Should be Ok now, the refresh will work for cases where the entry doesn't have the field yet.
